### ISSUE TITLE
Failure in CMake approach

### ISSUE THREAD

**Issue by folrent1896** [usnistgov/ChebTools#26]
Hi, I'm trying to use the CMake approach to install 'ChebTools' in an anaconda env. I have built the CMake file successfully. However, when I try the last step`cmake --build .` it failed with the following error information. Is this something related to the Compiler?

> Scanning dependencies of target ChebToolsCatchTests
[  8%] Building CXX object CMakeFiles/ChebToolsCatchTests.dir/tests/tests.cpp.o
In file included from /home/xiaodong/Downloads/ChebTools/tests/tests.cpp:4:0:
/home/**/Downloads/ChebTools/include/ChebTools/ChebTools.h:351:181: error: ‘dyadic_splitting’ function uses ‘auto’ type specifier without trailing return type
  const double xmin, const double xmax, const int M, const double tol, const int max_refine_passes = 8) {
                                                                                                      ^
/home/xiaodong/Downloads/ChebTools/include/ChebTools/ChebTools.h:351:181: note: deduced return type only available with -std=c++14 or -std=gnu++14
CMakeFiles/ChebToolsCatchTests.dir/build.make:62: recipe for target 'CMakeFiles/ChebToolsCatchTests.dir/tests/tests.cpp.o' failed
make[2]: *** [CMakeFiles/ChebToolsCatchTests.dir/tests/tests.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ChebToolsCatchTests.dir/all' failed
make[1]: *** [CMakeFiles/ChebToolsCatchTests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ianhbell** [comment]
What operating system and compiler do you use?

**Comment by ianhbell** [comment]
Bumped C++ version in 5fea566957f74579f18cc879ee0df7206358f74f

**Comment by folrent1896** [comment]
It's Ubuntu 18.04 and g++. I have installed 'ChebTools' successfully after setting the standard for C++ to c++14, Thanks a lot!
