### ISSUE TITLE
ChebTools/externals/pybind11    does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by iajzenszmi** [usnistgov/ChebTools#30]
ian@ian-HP-Stream-Laptop-11-y0XX:~/ChebTools/ChebTools$ sudo python3 setup.py install
[sudo] password for ian: 
running install
running bdist_egg
running egg_info
writing ChebTools.egg-info/PKG-INFO
writing dependency_links to ChebTools.egg-info/dependency_links.txt
writing top-level names to ChebTools.egg-info/top_level.txt
reading manifest file 'ChebTools.egg-info/SOURCES.txt'
writing manifest file 'ChebTools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
CMake Error at CMakeLists.txt:29 (add_subdirectory):
  The source directory

    /home/ian/ChebTools/ChebTools/externals/pybind11

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:30 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!
See also "/home/ian/ChebTools/ChebTools/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 37, in run
    self.build_extension(ext)
  File "setup.py", line 61, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/ian/ChebTools/ChebTools', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ian/ChebTools/ChebTools/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by ianhbell** [comment]
1. Make sure you do a recursive clone: https://github.com/usnistgov/ChebTools#from-a-cloned-repository
2. Don't do a sudo build (almost ever)

But really, there are binary wheels available for all platforms, so you can just do: pip install chebtools

**Comment by iajzenszmi** [comment]
"But really, there are binary wheels available for all platforms, so
you can just do: pip install chebtools"

***@***.***:~/ChebTools$ pip install chebtools
ERROR: Could not find a version that satisfies the requirement
chebtools (from versions: none)
ERROR: No matching distribution found for chebtools
***@***.***:~/ChebTools$ pip3 install chebtools
ERROR: Could not find a version that satisfies the requirement
chebtools (from versions: none)
ERROR: No matching distribution found for chebtools
***@***.***:~/ChebTools$ pip3 install ChebTools
ERROR: Could not find a version that satisfies the requirement
ChebTools (from versions: none)
ERROR: No matching distribution found for ChebTools
***@***.***:~/ChebTools$ cd
***@***.***:~$ pip install chebtools
ERROR: Could not find a version that satisfies the requirement
chebtools (from versions: none)
ERROR: No matching distribution found for chebtools
***@***.***:~$

**Comment by iajzenszmi** [comment]
pip install ChebTools-1.0.0-cp37-cp37m-win_amd64.whl
ERROR: ChebTools-1.0.0-cp37-cp37m-win_amd64.whl is not a supported
wheel on this platform.
***@***.***:~/Downloads$ pip install ChebTools
ERROR: Could not find a version that satisfies the requirement
ChebTools (from versions: none)
ERROR: No matching distribution found for ChebTools

No wheels available for Linux platform?

**Comment by ianhbell** [comment]
Well, I had in my mind that I had pushed wheels for ChebTools, but I guess that was another project I manage.  I set up the wheels, and binary wheels are now available on all platforms for version 1.8: https://pypi.org/project/ChebTools/1.8.0/#files .

So this time, a ``pip install ChebTools`` should do it.

**Comment by ianhbell** [comment]
Or you could also update the submodules and build yourself, but not necessary unless you want to.
